webapp/news/models.py
from webapp.db import db

class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=True)
    published = db.Column(db.DateTime, nullable=True)
    text = db.Column(db.Text, nullable=True)

    def __repr__(self):
        return '<News {} {} >'.format(self.title, self.url)

webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.db import db

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(36), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50))

    
    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'

    def __repr__(self):
        return '<User {}>'.format(self.username)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

class LoginForm(FlaskForm):
    username = StringField('Username', validators = [DataRequired()],render_kw={"class": "form-control"})
    password = PasswordField('Password', validators = [DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Remember me', default=True, render_kw={'class':'form-check-input'}) #checkbox
    submit = SubmitField('Send', render_kw={"class":"btn btn-primary"})

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators = [DataRequired()],render_kw={"class": "form-control"})
    email = StringField('Email', validators = [DataRequired(), Email()], render_kw={"class": "form-control"} )
    password = PasswordField('Password', validators = [DataRequired()], render_kw={"class": "form-control"} )
    password2 = PasswordField('Repeat password', validators = [DataRequired(), EqualTo('password')], render_kw={"class": "form-control"} )
    submit = SubmitField('Send', render_kw={"class":"btn btn-primary"})

webapp/__init__.py
from flask import Flask, blueprints, render_template, flash, redirect, url_for
from flask_login import LoginManager, current_user, login_required
from flask_migrate import Migrate

from webapp.user.views import blueprint as user_blueprint
from webapp.admin.views import blueprint as admin_blueprint
from webapp.news.views import blueprint as news_blueprint
from webapp.user.models import User
from webapp.db import db


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    migrate = Migrate(app, db)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'
    app.register_blueprint(user_blueprint)
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(news_blueprint)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app
    

webapp/admin/views.py
from flask  import Blueprint, render_template
from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@blueprint.route('/')
@admin_required
def admin_index():
    title = "HI, Admin!"
    return render_template('admin/index.html', page_title=title)

webapp/news/views.py
from webapp.news.models import News
from flask import Blueprint, render_template, current_app
from webapp.weather import weather_by_city

blueprint = Blueprint('news', __name__)

@blueprint.route('/')
def index():
    title = 'News Python'
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    news_list = News.query.order_by(News.published.desc()).all()
    return render_template('news/index.html',page_title=title, weather=weather, news_list=news_list)

webapp/user/views.py
from flask import Blueprint, blueprints, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, current_user, login_required

from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
        if current_user.is_authenticated:
            return redirect(url_for('news.index'))
        title = "Sign in"
        login_form = LoginForm()
        return render_template('user/login.html', page_title=title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('You are successfully loged in')
            return redirect(url_for('news.index'))

    flash('Invalid username or password')
    return redirect(url_for('user.login'))

@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    title = "Registration"
    form = RegistrationForm()
    return render_template('user/registration.html', page_title=title, form=form)

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('You are successfully loged out')
    return redirect(url_for('news.index'))

@blueprint.route('/precess-reg', methods=['POST'])
def process_reg():
    form=RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('You are successfully a user now')
        return redirect(url_for('user.login'))
    flash('Something is wrong in a form')
    return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include "menu.html" %}
    <div class="container">
        <h1>{{ page_title }}</h1>
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/index.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container">
        <h1>News website</h1>
        <div class="row">
            <div class="col-8">
                <h2>News</h2>
                {% for news in news_list %}
                <h3><a href = "{{ news.url }}">{{ news.title }}</a></h3>
                <p>{{ news.published }}</p>
                <hr /> 
                {% endfor %}
                
            </div>
            <div class="col-4">
                <h2>Weather forecast</h2>
                <h4>
                    {% if weather %}
                        Weather: {{ weather.temp_C }}, Feels like: {{ weather.FeelsLikeC }}
                    {% else %}
                        Weather service is currently inactive
                    {% endif %}
                </h4>
            </div>
        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">News Python</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="/">Main Page</a>
        </li>

      </ul>
    </div>
  <form class="d-flex">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Искать</button>
  </form>
  <ul class="navbar-nav">
    {% if current_user.is_authenticated %}
      <li class="nav-item">
        <span class="nav-link">Hello, {{ current_user.username }}!</span>
      </li>
      {% if current_user.is_admin %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Administration</a>
      </li> 
      {% endif %}

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
      </li>  
    {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.register') }}">Registration</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
      </li>
    {% endif %}
  </ul>

</nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}

webapp/templates/news/index.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-8">
            {% include ('messages.html') %}
            <h2>News</h2>
            {% for news in news_list %}
            <h3><a href = "{{ news.url }}">{{ news.title }}</a></h3>
            <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
            <hr /> 
            {% endfor %}
        </div>
        <div class="col-4">
            <h2>Weather forecast</h2>
            <h4>
                {% if weather %}
                    Temperature: {{ weather.temp_C }} °С <br>
                    Feels like: {{ weather.FeelsLikeC }} °С
                {% else %}
                    Weather service is currently inactive
                {% endif %}
            </h4>
        </div>
    </div>
{% endblock %}

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-4">
            {% include('messages.html') %}
            <form action="{{ url_for('user.process_login') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password() }}
                </div>
                <div class="form-group form-check">
                    {{ form.remember_me() }}
                    {{ form.remember_me.label(class_='form-check-label') }}
                </div>
                {{ form.submit() }}
            </form>
        </div>
        <div class="col-8">

        </div>
    </div>
{% endblock %}

webapp/templates/user/registration.html
{% extends "base.html" %}

{% block content %}
    {% include('messages.html') %}
    <div class="row">
        <div class="col-4">

            <form action="{{ url_for('user.process_reg') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.email.label }}
                    {{ form.email() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password() }}
                </div>
                <div class="form-group">
                    {{ form.password2.label }}
                    {{ form.password2() }}
                </div>
                {{ form.submit() }}
            </form>
        </div>
        <div class="col-8">

        </div>
    </div>
{% endblock %}